// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.mzj.netty.ssy._08_grpc;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mzj.netty.ssy._08_grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *repeated表示集合类型，这里表示服务器端向客户端返回的是一个集合类型，集合中元素是StudentResponse
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <pre>
   *repeated表示集合类型，这里表示服务器端向客户端返回的是一个集合类型，集合中元素是StudentResponse
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <pre>
   *repeated表示集合类型，这里表示服务器端向客户端返回的是一个集合类型，集合中元素是StudentResponse
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <pre>
   *repeated表示集合类型，这里表示服务器端向客户端返回的是一个集合类型，集合中元素是StudentResponse
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <pre>
   *repeated表示集合类型，这里表示服务器端向客户端返回的是一个集合类型，集合中元素是StudentResponse
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
