// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.mzj.netty.ssy._08_grpc;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzj_netty_ssy__08_grpc_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzj_netty_ssy__08_grpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzj_netty_ssy__08_grpc_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzj_netty_ssy__08_grpc_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzj_netty_ssy__08_grpc_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzj_netty_ssy__08_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzj_netty_ssy__08_grpc_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzj_netty_ssy__08_grpc_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzj_netty_ssy__08_grpc_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzj_netty_ssy__08_grpc_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzj_netty_ssy__08_grpc_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzj_netty_ssy__08_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzj_netty_ssy__08_grpc_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzj_netty_ssy__08_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\032com.mzj.netty.ssy._08_g" +
      "rpc\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMy" +
      "Response\022\020\n\010realname\030\002 \001(\t\"\035\n\016StudentReq" +
      "uest\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004" +
      "name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"[\n" +
      "\023StudentResponseList\022D\n\017studentResponse\030" +
      "\001 \003(\0132+.com.mzj.netty.ssy._08_grpc.Stude" +
      "ntResponse\"%\n\rStreamRequest\022\024\n\014request_i" +
      "nfo\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\rresponse_" +
      "info\030\001 \001(\t2\317\003\n\016StudentService\022h\n\025GetReal" +
      "NameByUsername\022%.com.mzj.netty.ssy._08_g" +
      "rpc.MyRequest\032&.com.mzj.netty.ssy._08_gr" +
      "pc.MyResponse\"\000\022o\n\020GetStudentsByAge\022*.co" +
      "m.mzj.netty.ssy._08_grpc.StudentRequest\032" +
      "+.com.mzj.netty.ssy._08_grpc.StudentResp" +
      "onse\"\0000\001\022{\n\030GetStudentsWrapperByAges\022*.c" +
      "om.mzj.netty.ssy._08_grpc.StudentRequest" +
      "\032/.com.mzj.netty.ssy._08_grpc.StudentRes" +
      "ponseList\"\000(\001\022e\n\006BiTalk\022).com.mzj.netty." +
      "ssy._08_grpc.StreamRequest\032*.com.mzj.net" +
      "ty.ssy._08_grpc.StreamResponse\"\000(\0010\001B,\n\032" +
      "com.mzj.netty.ssy._08_grpcB\014StudentProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_mzj_netty_ssy__08_grpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mzj_netty_ssy__08_grpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzj_netty_ssy__08_grpc_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_mzj_netty_ssy__08_grpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mzj_netty_ssy__08_grpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzj_netty_ssy__08_grpc_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_mzj_netty_ssy__08_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mzj_netty_ssy__08_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzj_netty_ssy__08_grpc_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_mzj_netty_ssy__08_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_mzj_netty_ssy__08_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzj_netty_ssy__08_grpc_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_mzj_netty_ssy__08_grpc_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_mzj_netty_ssy__08_grpc_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzj_netty_ssy__08_grpc_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_com_mzj_netty_ssy__08_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_mzj_netty_ssy__08_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzj_netty_ssy__08_grpc_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_com_mzj_netty_ssy__08_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_mzj_netty_ssy__08_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzj_netty_ssy__08_grpc_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
