// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.mzj.netty.ssy._08_grpc;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mzj.netty.ssy._08_grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *protobuf中集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.mzj.netty.ssy._08_grpc.StudentResponse> 
      getStudentResponseList();
  /**
   * <pre>
   *protobuf中集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  com.mzj.netty.ssy._08_grpc.StudentResponse getStudentResponse(int index);
  /**
   * <pre>
   *protobuf中集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <pre>
   *protobuf中集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.mzj.netty.ssy._08_grpc.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <pre>
   *protobuf中集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.mzj.netty.ssy._08_grpc.StudentResponse studentResponse = 1;</code>
   */
  com.mzj.netty.ssy._08_grpc.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
