// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.mzj.netty.ssy._08_grpc;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mzj.netty.ssy._08_grpc.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
